### ISSUE TITLE
Memory measure

### ISSUE THREAD

**Issue by sjdingcn** [raven38/EfficientDynamic3DGaussian#11]
Thank you for this great work.
One question: how do you measure the memory cost?

Thank you

**Comment by raven38** [comment]
We measure the memory cost by checking the file size of saved models.  The memory cost of our method depends on the value of L. Since the model is initialized with fixed L, we modified 

https://github.com/raven38/EfficientDynamic3DGaussian/blob/c79a9f00970f293e6ff354e71c43c13f4191a676/scene/dataset_readers.py#L887

https://github.com/raven38/EfficientDynamic3DGaussian/blob/c79a9f00970f293e6ff354e71c43c13f4191a676/scene/dataset_readers.py#L763


https://github.com/raven38/EfficientDynamic3DGaussian/blob/c79a9f00970f293e6ff354e71c43c13f4191a676/scene/dataset_readers.py#L553



https://github.com/raven38/EfficientDynamic3DGaussian/blob/c79a9f00970f293e6ff354e71c43c13f4191a676/scene/dataset_readers.py#L407

https://github.com/raven38/EfficientDynamic3DGaussian/blob/c79a9f00970f293e6ff354e71c43c13f4191a676/scene/dataset_readers.py#L265
