### ISSUE TITLE
Problem about train.py

### ISSUE THREAD

**Issue by cdfan0627** [raven38/EfficientDynamic3DGaussian#5]
Hellow

I appreciate your work very much, but I face the following problem when I was training hypernerf dataset.
The following is my command 
python train.py -s data/hypernerf/chickchicken --model_path "output/hypernerf/chickchicken" --eval

<img width="613" alt="image" src="https://github.com/raven38/EfficientDynamic3DGaussian/assets/144821204/c6666907-ff54-48a2-b36a-d0f6814f8c7a">

**Comment by josephldobson** [comment]
I also have this issue!

**Comment by ana42742** [comment]
Hey, I had the same issue. This error is occurring because of the return value for function rasterizer() called on line 115, under /EfficientDynamic3DGaussian/gaussian_renderer/__init__.py: 

```
rendered_image, radii = rasterizer(
        means3D = means3D,
        means2D = means2D,
        shs = shs,
        colors_precomp = colors_precomp,
        opacities = opacity,
        scales = scales,
        rotations = rotations,
        cov3D_precomp = cov3D_precomp)
```

This returned value is `rendered_image, radii, depth `, i.e. 3 values as opposed to just `rendered_image, radii`, i.e. 2 values. So I just updated line 115 from
`rendered_image, radii = rasterizer(`
to
`rendered_image, radii, depth = rasterizer(`
and it seems to be working fine for me.

**Comment by raven38** [comment]
@ana42742 Thank you for the suggestion. 
Our community has multiple rasterizers with different interfaces like 
https://github.com/graphdeco-inria/diff-gaussian-rasterization/
https://github.com/JonathonLuiten/diff-gaussian-rasterization-w-depth

It seems that if you use JonathonLuiten's rasterizer, the returned values are 3 values. 
Please adapt the code to your rasterizer. 

And, sorry for the ambiguous instructions in README.
